Repository NVIDIA/earth2studio, pull requests merged in 2024-06, with the labels that each got.

#67 Model Package Update to improve Model file caching
  CHANGELOG.md
  docs/userguide/advanced/auto.md
  earth2studio/models/auto.py
  earth2studio/models/dx/climatenet.py
  earth2studio/models/dx/corrdiff.py
  earth2studio/models/dx/precipitation_afno.py
  earth2studio/models/px/dlwp.py
  earth2studio/models/px/fcn.py
  earth2studio/models/px/fengwu.py
  earth2studio/models/px/fuxi.py
  earth2studio/models/px/pangu.py
  earth2studio/models/px/sfno.py
  pyproject.toml
  test/models/dx/test_corrdiff.py
  test/models/test_auto_models.py
Labels: 3 - Ready for Review

#73 Pytest improvement, Bug Fixes and Documentation Update
  docs/userguide/about/install.md
  docs/userguide/developer/documentation.md
  docs/userguide/developer/overview.md
  docs/userguide/developer/testing.md
  docs/userguide/index.md
  earth2studio/models/auto.py
  earth2studio/models/batch.py
  earth2studio/perturbation/lagged.py
  test/conftest.py
  test/models/px/test_dlwp.py
  test/models/px/test_fcn.py
  test/models/px/test_sfno.py
  test/models/test_auto_models.py
Labels: 2 - In Progress

#76 Updating IMERG total precip data to meters
  earth2studio/data/imerg.py
  earth2studio/lexicon/base.py
  earth2studio/lexicon/imerg.py
Labels: 2 - In Progress

#79 Climatenet Coordinate Bug Fix
  earth2studio/models/dx/climatenet.py
  test/models/dx/test_climatenet.py
Labels: bug

#80 Updating input coord API to functions
  CHANGELOG.md
  docs/userguide/about/data.md
  docs/userguide/advanced/batch.md
  earth2studio/models/batch.py
  earth2studio/models/dx/base.py
  earth2studio/models/dx/climatenet.py
  earth2studio/models/dx/corrdiff.py
  earth2studio/models/dx/identity.py
  earth2studio/models/dx/precipitation_afno.py
  earth2studio/models/px/base.py
  earth2studio/models/px/dlwp.py
  earth2studio/models/px/fcn.py
  earth2studio/models/px/fengwu.py
  earth2studio/models/px/fuxi.py
  earth2studio/models/px/pangu.py
  earth2studio/models/px/persistence.py
  earth2studio/models/px/sfno.py
  earth2studio/run.py
  examples/04_corrdiff_inference.py
  examples/07_seasonal_statistics.py
  examples/extend/01_custom_prognostic.py
  examples/extend/02_custom_diagnostic.py
  examples/extend/03_custom_datasource.py
  test/models/dx/test_climatenet.py
  test/models/dx/test_corrdiff.py
  test/models/dx/test_precip_afno.py
  test/models/px/test_dlwp.py
  test/models/px/test_fcn.py
  test/models/px/test_fengwu.py
  test/models/px/test_fuxi.py
  test/models/px/test_pangu.py
  test/models/px/test_persistence.py
  test/models/px/test_sfno.py
  test/models/test_auto_models.py
  test/models/test_batch.py
  test/run/test_diagnostic.py
Labels: 2 - In Progress
