Repository NVIDIA/earth2studio, pull requests merged in 2025-05, with the labels that each got.

#285 Install Doc Updates / Improvements
  docs/modules/models.rst
  docs/userguide/about/install.md
  docs/userguide/support/troubleshooting.md
Labels: 2 - In Progress

#293 Reproducibility Test for the HENS workflow
  earth2studio/data/__init__.py
  earth2studio/data/const.py
  earth2studio/perturbation/hcbv.py
  recipes/hens/.gitignore
  recipes/hens/README.md
  recipes/hens/cfg/helene.yaml
  recipes/hens/cfg/reproduce_helene_batches.yaml
  recipes/hens/pyproject.toml
  recipes/hens/src/hens_ensemble.py
  recipes/hens/test/Makefile
  recipes/hens/test/README.md
  recipes/hens/test/compare_tracks.py
  recipes/hens/test/test_reprod.py
  test/data/test_constant.py
  test/perturbation/test_hcbv.py
Labels: 4 - In Review

#307 Correcting Stormcast coordinates
  CHANGELOG.md
  earth2studio/data/__init__.py
  earth2studio/data/gefs.py
  earth2studio/data/gfs.py
  earth2studio/data/hrrr.py
  earth2studio/data/rand.py
  earth2studio/data/utils.py
  earth2studio/data/wb2.py
  earth2studio/models/px/dlesym.py
  earth2studio/models/px/sfno.py
  earth2studio/models/px/stormcast.py
  earth2studio/run.py
  earth2studio/utils/coords.py
  examples/09_stormcast_example.py
  examples/10_stormcast_ensemble_example.py
  pyproject.toml
  test/data/test_data_utils.py
  test/data/test_random.py
  test/models/px/test_stormcast.py
  uv.lock
Labels: 2 - In Progress

#256 Add GraphCast (1 degree model)
  .gitlab-ci.yml
  CHANGELOG.md
  Makefile
  docs/modules/models.rst
  docs/userguide/about/install.md
  earth2studio/lexicon/arco.py
  earth2studio/lexicon/base.py
  earth2studio/lexicon/wb2.py
  earth2studio/models/px/__init__.py
  earth2studio/models/px/graphcast_small.py
  earth2studio/utils/imports.py
  pyproject.toml
  test/models/px/test_graphcast.py
  test/models/test_auto_models.py
  uv.lock
Labels: 1 - On Deck, ! - Release

#320 AFNO solar radiation diagnostic model
  CHANGELOG.md
  docs/modules/models.rst
  docs/userguide/about/install.md
  docs/userguide/advanced/lexicon.md
  earth2studio/data/gfs.py
  earth2studio/lexicon/gfs.py
  earth2studio/models/dx/__init__.py
  earth2studio/models/dx/solarradiation_afno.py
  earth2studio/models/nn/afno_ssrd.py
  pyproject.toml
  test/models/dx/test_solarradiation_afno.py
  test/models/test_auto_models.py
  uv.lock
Labels: ! - Release
