Repository NVIDIA/earth2studio, pull requests merged in 2025-04, with the labels that each got.

#244 Add derived variable diagnostics
  CHANGELOG.md
  docs/modules/models.rst
  docs/userguide/about/install.md
  earth2studio/lexicon/base.py
  earth2studio/models/dx/__init__.py
  earth2studio/models/dx/derived.py
  pyproject.toml
  test/models/dx/test_derived.py
  uv.lock
Labels: 4 - In Review

#254 Adding Surface relative humidity diagnostic
  CHANGELOG.md
  docs/modules/models.rst
  docs/userguide/developer/overview.md
  docs/userguide/support/faq.md
  earth2studio/lexicon/gfs.py
  earth2studio/models/dx/__init__.py
  earth2studio/models/dx/derived.py
  test/models/dx/test_derived.py
Labels: 4 - In Review

#246 Windgust AFNO Diagnostic model
  .licenses/summary.md
  CHANGELOG.md
  Makefile
  docs/modules/models.rst
  docs/userguide/about/install.md
  docs/userguide/index.md
  docs/userguide/support/faq.md
  docs/userguide/support/troubleshooting.md
  earth2studio/lexicon/gfs.py
  earth2studio/lexicon/wb2.py
  earth2studio/models/dx/__init__.py
  earth2studio/models/dx/wind_gust.py
  pyproject.toml
  test/models/dx/test_wind_gust.py
  test/models/test_auto_models.py
  uv.lock
Labels: 4 - In Review

#247 ModAFNO Interpolation Model
  CHANGELOG.md
  docs/modules/models.rst
  docs/userguide/about/install.md
  earth2studio/models/px/__init__.py
  earth2studio/models/px/interpmodafno.py
  examples/12_prognostic_temporal_interpolation.py
  pyproject.toml
  test/models/px/test_aurora.py
  test/models/px/test_interpmodafno.py
  test/models/test_auto_models.py
  uv.lock
Labels: 2 - In Progress

#274 HENS Mini Example
  .gitignore
  CHANGELOG.md
  Makefile
  docs/modules/perturbation.rst
  earth2studio/perturbation/hcbv.py
  examples/08_distributed_manager.py
  examples/11_huge_ensembles.py
  examples/12_temporal_interpolation.py
  examples/13_cyclone_tracking.py
  test/perturbation/test_hcbv.py
Labels: 4 - In Review

#276 Removing pickle load from Aurora
  CHANGELOG.md
  earth2studio/models/px/aurora.py
Labels: 2 - In Progress

#279 ARCO update for async
  CHANGELOG.md
  earth2studio/data/arco.py
  earth2studio/data/utils.py
Labels: 3 - Ready for Review
